### ISSUE TITLE
Error installation TS 5.1 and UnoCSS 0.53

### ISSUE THREAD

**Issue by eshimischi** [StarLederer/windblade#10]
<img width="760" alt="Screenshot 2023-06-14 at 00 33 11" src="https://github.com/StarLederer/windblade/assets/983201/f09b39af-5512-4c03-922d-691af4f74693">

`Type 'Preset<Theme>' is not assignable to type 'Preset<{}> | Preset<{}>[]'.
  Type 'Preset<Theme>' is not assignable to type 'Preset<{}>'.
    Types of property 'rules' are incompatible.
      Type 'Rule<Theme>[] | undefined' is not assignable to type 'Rule<{}>[] | undefined'.
        Type 'Rule<Theme>[]' is not assignable to type 'Rule<{}>[]'.
          Type 'Rule<Theme>' is not assignable to type 'Rule<{}>'.
            Type '[RegExp, DynamicMatcher<Theme>]' is not assignable to type 'Rule<{}>'.
              Type '[RegExp, DynamicMatcher<Theme>]' is not assignable to type '[string, CSSObject | CSSEntries] | [RegExp, DynamicMatcher<{}>]'.
                Type '[RegExp, DynamicMatcher<Theme>]' is not assignable to type '[string, CSSObject | CSSEntries]'.
                  Type at position 0 in source is not compatible with type at position 0 in target.
                    Type 'RegExp' is not assignable to type 'string'.ts(2322)`

**Comment by eshimischi** [comment]
Tried it in unocss.config.ts with exactly the same error

**Comment by eshimischi** [comment]
Here is my implementation with the current error https://github.com/eshimischi/windblade-ts-5.1

**Comment by StarLederer** [comment]
Thank you for the report and the reproduction repo! I've encountered similar issues myself so I'm glad to inform you this should be just a type error and the presets should work regardless. Of course, I am still going to fix this but you might have to wait a bit.

I have generally walked back on my opinion on atomic CSS and am planning to discontinue most of Windblade or offer it to be taken over, however, there are some big changes I initiated that I want to complete and It would be hard to publish a new version based on UnoCSS 0.53 before finishing them

**Comment by eshimischi** [comment]
> Thank you for the report and the reproduction repo! I've encountered similar issues myself so I'm glad to inform you this should be just a type error and the presets should work regardless. Of course, I am still going to fix this but you might have to wait a bit.
> 
> I have generally walked back on my opinion on atomic CSS and am planning to discontinue most of Windblade or offer it to be taken over, however, there are some big changes I initiated that I want to complete and It would be hard to publish a new version based on UnoCSS 0.53 before finishing them

thanks for your reply, i'm not rushing you, tyt! just very impressed how good your preset is and wanted to use in my TS project right now, but stuck with this annoying type error, so ... looking forward for the changes and fix! Best of luck

**Comment by StarLederer** [comment]
`presetMiniVariants` is already fixed, please update.

`presetWindblade` was broken for a different reason that was a bit tricky to catch but I've fixed it and will publish an update later today. There are more changes coming than just the fix, keep an eye out for this! I'll post another comment once the update is actually up.

Thank you once again for the report! It motivated me to finally finish a couple of things that I started a while ago.

**Comment by eshimischi** [comment]
> `presetMiniVariants` is already fixed, please update.
> 
> `presetWindblade` was broken for a different reason that was a bit tricky to catch but I've fixed it and will publish an update later today. There are more changes coming than just the fix, keep an eye out for this! I'll post another comment once the update is actually up.
> 
> Thank you once again for the report! It motivated me to finally finish a couple of things that I started a while ago

my pleasure! thanks for cooperation, looking forward to get beta.4 from npm repo, still wanting it in my TS project :)

**Comment by StarLederer** [comment]
Just published beta.4!

`unocss-preset-windblade` should work the same but I recommend switching to `@windblade/unocss-preset`. `unocss-preset-windblade` now exists mainly for legacy reasons and simply re-exports `@windblade/unocss-preset`.

The color framework and the`$` syntax are also available separately now and can be used together with [@unocss/preset-wind](https://unocss.dev/presets/wind) to avoid most of my half-baked Tailwind re-implementation. You won't get my grid utils and logical properties and values this way though.

The package is a little difficult to maintain alone so I might have accidentally broken something so please try it out and let me know if you are able to successfully build your project. I'll close the issue upon your confirmation

**Comment by eshimischi** [comment]
> Just published beta.4!
> 
> `unocss-preset-windblade` should work the same but I recommend switching to `@windblade/unocss-preset`. `unocss-preset-windblade` now exists mainly for legacy reasons and simply re-exports `@windblade/unocss-preset`.
> 
> The color framework and the `$` syntax are also available separately now and can be used together with [@unocss/preset-wind](https://unocss.dev/presets/wind) to avoid most of my half-baked Tailwind re-implementation. You won't get my grid utils and logical properties and values this way though.
> 
> The package is a little difficult to maintain alone so I might have accidentally broken something so please try it out and let me know if you are able to successfully build your project. I'll close the issue upon your confirmation

yes, already added it to my project, testing. Thanks!

**Comment by eshimischi** [comment]
> The color framework and the $ syntax are also available separately now and can be used together with [@unocss/preset-wind](https://unocss.dev/presets/wind) to avoid most of my half-baked Tailwind re-implementation. You won't get my grid utils and logical properties and values this way though.

Would you please describe it more detailed because i didn't get how to install it separately. Thanks again!

**Comment by StarLederer** [comment]
You'll find instructions in updated [docs](https://starlederer.github.io/windblade/?navigation=%2Fdocs). Each module has separate installation instructions. Also, when you are on any of the docs pages you are able to switch the module.

I am actually noticing rn that I got the package names wrong 😝. It should be `@windblade/unocss-preset-color` instead of `@windblade/preset-color` and same goes for 'dollars'. Please double check the [npm registry](https://www.npmjs.com/org/windblade) if you are having trouble finding the modules. I'll update the docs when I get a chance.

**Comment by eshimischi** [comment]
I've updated my repro code here - all good! https://github.com/eshimischi/windblade-ts-5.1

**Comment by eshimischi** [comment]
<img width="1058" alt="Screenshot 2023-06-26 at 09 41 40" src="https://github.com/StarLederer/windblade/assets/983201/183b1f97-b14f-430c-ad95-d9e68418b6cb">
But not in my project tho :(

**Comment by StarLederer** [comment]
I wonder if this is caused by UnoCSS version mismatch. Could you please try again with UnoCSS v0.53.3 (if not already)

**Comment by eshimischi** [comment]
> I wonder if this is caused by UnoCSS version mismatch. Could you please try again with UnoCSS v0.53.3 (if not already)

yes, seems so, still checking my workspace and deps.

**Comment by eshimischi** [comment]
Strangest thing is default UnoCSS presets are working without issues

<img width="1048" alt="Screenshot 2023-06-26 at 16 28 33" src="https://github.com/StarLederer/windblade/assets/983201/e746832e-8b2c-4235-893c-a067f0b8fdbf">

**Comment by StarLederer** [comment]
This error occurs when using "incompatible" presets, that is, ones that are either not `Theme` or extend `Theme` in different ways (that is, in fact, why the error happened originally, windblade required a `windblade` object to be present in the theme so if you added other presets that didn't do the same it was deemed incompatible. Beta.4 fixed this by making the object optional).

You are using UnoCSS 0.53.4 while the preset is made for 0.53.3 so maybe the typechecker sees those `Theme` types as incompatible even if nothing actually changed.

I think your problem will be solved if you downgrade to 0.53.3.

Alternatively, you can try to override the dependency in Windblade by adding this to your `package.json`

```json
"pnpm": {
  "overrides": {
    "unocss": "0.53.4"
  }
}
```

**Comment by eshimischi** [comment]
> ```json
> "pnpm": {
>   "overrides": {
>     "unocss": "0.53.4"
>   }
> }
> ```

yes, indeed, i've solved the issue with sticking to UnoCSS 0.53.3. Thanks!

**Comment by eshimischi** [comment]
And the very last question - is it okay to use all the presets: WindBlade, Color, Dollar together with/without Unocss Wind preset (Tailwind) ?

<img width="706" alt="Screenshot 2023-06-26 at 21 56 07" src="https://github.com/StarLederer/windblade/assets/983201/689b78f7-9a6a-434b-8dcd-9c86fac9213c">

**Comment by StarLederer** [comment]
Great to hear that it works now. I'll add a note about this to the documentation
