### ISSUE TITLE
can't install your preset

### ISSUE THREAD

**Issue by jojojojojoj5564656465465** [StarLederer/windblade#3]
ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/unocss-preset-windblade: Not Found - 404

This error happened while installing a direct dependency of /home/manjaro/DEV/astro uno/uno

unocss-preset-windblade is not in the npm registry, or you have no permission to fetch it.

No authorization header was set for the request.
Progress: resolved 3, reused 3, downloaded 0, added 0

**Comment by StarLederer** [comment]
Please note that after v2.0.0-alpha there is an additional dependency "culori" that you also need to install into your project if you are using Windblade buildless

**Comment by jojojojojoj5564656465465** [comment]
Would you be abble to add this to Windblade ;

![image](https://user-images.githubusercontent.com/45184918/218272676-c5abd95b-be16-4c59-a379-b23f7b489de2.png)

**Comment by StarLederer** [comment]
Please open new issues for new feature requests. I moved this one to #6 and will hide your comment.

**Comment by StarLederer** [comment]
For those who have been referred to this issue for pre-release installation: You do not need these instructions anymore because the preset is now available on NPM.
